import "@/styles/globals.css";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by rent app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Rent App</title>
      </Head>
      <div
        className={`bg-gray-50 text-indigo-900 overflow-x-hidden ${inter.className}`}
      >
        <Component {...pageProps} />
      </div>
    </>
  );
}
